In [9]:
import numpy as np

a=np.array([1,2,3]) # create a rank 1 array
print(type(a))      # prints <class 'numpy.ndarray'>
print(a.shape)      # prints <class (3,) returns tuple
print(a[0],a[1],a[2])
a[0]=5              # Change an element of the array
print(a)

b = np.array([[1,2,3],[4,5,6]]) # Create a rank 2 array
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [20]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.64706617 0.34624539]
 [0.83756482 0.6503932 ]]
